/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "include/protos/vex.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(TerriBullDevices_DeviceHeader, TerriBullDevices_DeviceHeader, AUTO)


PB_BIND(TerriBullDevices_MotorDevice, TerriBullDevices_MotorDevice, AUTO)


PB_BIND(TerriBullDevices_RotationSensorDevice, TerriBullDevices_RotationSensorDevice, AUTO)


PB_BIND(TerriBullDevices_IMUAccel, TerriBullDevices_IMUAccel, AUTO)


PB_BIND(TerriBullDevices_IMUDevice, TerriBullDevices_IMUDevice, AUTO)


PB_BIND(TerriBullDevices_AnalogDevice, TerriBullDevices_AnalogDevice, AUTO)


PB_BIND(TerriBullDevices_MotorInitializeCallbackData, TerriBullDevices_MotorInitializeCallbackData, AUTO)


PB_BIND(TerriBullDevices_MotorSetVelocityCallbackData, TerriBullDevices_MotorSetVelocityCallbackData, AUTO)


PB_BIND(TerriBullDevices_RotationSensorInitializeCallbackData, TerriBullDevices_RotationSensorInitializeCallbackData, AUTO)


PB_BIND(TerriBullDevices_RotationSensorSetPositionCallbackData, TerriBullDevices_RotationSensorSetPositionCallbackData, AUTO)


PB_BIND(TerriBullDevices_RotationSensorResetPositionCallbackData, TerriBullDevices_RotationSensorResetPositionCallbackData, AUTO)


PB_BIND(TerriBullDevices_DeviceValue, TerriBullDevices_DeviceValue, AUTO)


PB_BIND(TerriBullDevices_FunctionCall, TerriBullDevices_FunctionCall, AUTO)


PB_BIND(TerriBullDevices_ReturnData, TerriBullDevices_ReturnData, AUTO)







#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

