/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_TERRIBULLDEVICES_INCLUDE_PROTOS_VEX_PB_H_INCLUDED
#define PB_TERRIBULLDEVICES_INCLUDE_PROTOS_VEX_PB_H_INCLUDED
#include <pb.h>
#include <pb_encode.h>
#include <pb_decode.h>
#include <pb_common.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _TerriBullDevices_DeviceType {
    TerriBullDevices_DeviceType_DEVICE_NONE = 0,
    TerriBullDevices_DeviceType_DEVICE_MOTOR = 2,
    TerriBullDevices_DeviceType_DEVICE_ROTATION = 4,
    TerriBullDevices_DeviceType_DEVICE_IMU = 6,
    TerriBullDevices_DeviceType_DEVICE_DISTANCE = 7,
    TerriBullDevices_DeviceType_DEVICE_RADIO = 8,
    TerriBullDevices_DeviceType_DEVICE_VISION = 11,
    TerriBullDevices_DeviceType_DEVICE_ADI = 12,
    TerriBullDevices_DeviceType_DEVICE_OPTICAL = 16,
    TerriBullDevices_DeviceType_DEVICE_GPS = 20,
    TerriBullDevices_DeviceType_DEVICE_SERIAL = 129
} TerriBullDevices_DeviceType;

typedef enum _TerriBullDevices_MotorGearSet {
    TerriBullDevices_MotorGearSet_GEARSET_36 = 0, /* 100 RPM, Red gear set */
    TerriBullDevices_MotorGearSet_GEARSET_18 = 1, /* 200 RPM, Green gear set */
    TerriBullDevices_MotorGearSet_GEARSET_06 = 2, /* 600 RPM, Blue gear set */
    TerriBullDevices_MotorGearSet_GEARSET_INVALID = 2147483647 /* INT32_MAX, indicating an invalid value */
} TerriBullDevices_MotorGearSet;

typedef enum _TerriBullDevices_MotorBrakeMode {
    TerriBullDevices_MotorBrakeMode_BRAKE_MODE_COAST = 0,
    TerriBullDevices_MotorBrakeMode_BRAKE_MODE_BRAKE = 1,
    TerriBullDevices_MotorBrakeMode_BRAKE_MODE_HOLD = 2
} TerriBullDevices_MotorBrakeMode;

typedef enum _TerriBullDevices_DeviceCallbackReturnCode {
    TerriBullDevices_DeviceCallbackReturnCode_SUCCESS = 0,
    TerriBullDevices_DeviceCallbackReturnCode_DEVICE_TYPE_MISMATCH = 1,
    TerriBullDevices_DeviceCallbackReturnCode_DEVICE_NOT_EXIST = 2
} TerriBullDevices_DeviceCallbackReturnCode;

/* Struct definitions */
typedef struct _TerriBullDevices_DeviceHeader {
    TerriBullDevices_DeviceType pros_device_type;
    uint32_t port; /* Changed from uint8 to uint32 because protobuf doesn't have uint8 */
} TerriBullDevices_DeviceHeader;

typedef struct _TerriBullDevices_MotorDevice {
    bool has_header;
    TerriBullDevices_DeviceHeader header;
    float velocity;
    float current_draw;
    TerriBullDevices_MotorGearSet gear_set;
    TerriBullDevices_MotorBrakeMode break_mode; /* Other motor-specific members can be added here as needed. */
} TerriBullDevices_MotorDevice;

typedef struct _TerriBullDevices_IMUAccel {
    float ax;
    float ay;
    float az;
} TerriBullDevices_IMUAccel;

typedef struct _TerriBullDevices_IMUDevice {
    bool has_header;
    TerriBullDevices_DeviceHeader header;
    float roll;
    float yaw;
    float pitch;
    bool has_accel;
    TerriBullDevices_IMUAccel accel;
} TerriBullDevices_IMUDevice;

typedef struct _TerriBullDevices_AnalogDevice {
    bool has_header;
    TerriBullDevices_DeviceHeader header;
    float value;
} TerriBullDevices_AnalogDevice;

/* --- CALLBACK FUNCTIONS --- */
typedef struct _TerriBullDevices_MotorInitializeCallbackData {
    uint32_t port;
    TerriBullDevices_MotorGearSet GEAR_SET;
    TerriBullDevices_MotorBrakeMode BREAK_MODE;
} TerriBullDevices_MotorInitializeCallbackData;

typedef struct _TerriBullDevices_MotorSetVelocityCallbackData {
    uint32_t port;
    int32_t velocity; /* Assuming velocity can be negative, hence int32. */
} TerriBullDevices_MotorSetVelocityCallbackData;

/* Message to get the device values, which contains one of the Devices (Motor, IMU, Analog) */
typedef struct _TerriBullDevices_DeviceValue {
    pb_size_t which_device;
    union {
        TerriBullDevices_MotorDevice motorDevice;
        TerriBullDevices_IMUDevice imuDevice;
        TerriBullDevices_AnalogDevice analogDevice;
    } device;
} TerriBullDevices_DeviceValue;

/* Message which calls a function and contains one of the callback data structs */
typedef struct _TerriBullDevices_FunctionCall {
    pb_size_t which_callbackData;
    union {
        TerriBullDevices_MotorInitializeCallbackData motorInitializeData;
        TerriBullDevices_MotorSetVelocityCallbackData motorSetVelocityData; /* ... TODO: ADD MORE CALLBACKS */
    } callbackData;
} TerriBullDevices_FunctionCall;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _TerriBullDevices_DeviceType_MIN TerriBullDevices_DeviceType_DEVICE_NONE
#define _TerriBullDevices_DeviceType_MAX TerriBullDevices_DeviceType_DEVICE_SERIAL
#define _TerriBullDevices_DeviceType_ARRAYSIZE ((TerriBullDevices_DeviceType)(TerriBullDevices_DeviceType_DEVICE_SERIAL+1))

#define _TerriBullDevices_MotorGearSet_MIN TerriBullDevices_MotorGearSet_GEARSET_36
#define _TerriBullDevices_MotorGearSet_MAX TerriBullDevices_MotorGearSet_GEARSET_INVALID
#define _TerriBullDevices_MotorGearSet_ARRAYSIZE ((TerriBullDevices_MotorGearSet)(TerriBullDevices_MotorGearSet_GEARSET_INVALID+1))

#define _TerriBullDevices_MotorBrakeMode_MIN TerriBullDevices_MotorBrakeMode_BRAKE_MODE_COAST
#define _TerriBullDevices_MotorBrakeMode_MAX TerriBullDevices_MotorBrakeMode_BRAKE_MODE_HOLD
#define _TerriBullDevices_MotorBrakeMode_ARRAYSIZE ((TerriBullDevices_MotorBrakeMode)(TerriBullDevices_MotorBrakeMode_BRAKE_MODE_HOLD+1))

#define _TerriBullDevices_DeviceCallbackReturnCode_MIN TerriBullDevices_DeviceCallbackReturnCode_SUCCESS
#define _TerriBullDevices_DeviceCallbackReturnCode_MAX TerriBullDevices_DeviceCallbackReturnCode_DEVICE_NOT_EXIST
#define _TerriBullDevices_DeviceCallbackReturnCode_ARRAYSIZE ((TerriBullDevices_DeviceCallbackReturnCode)(TerriBullDevices_DeviceCallbackReturnCode_DEVICE_NOT_EXIST+1))

#define TerriBullDevices_DeviceHeader_pros_device_type_ENUMTYPE TerriBullDevices_DeviceType

#define TerriBullDevices_MotorDevice_gear_set_ENUMTYPE TerriBullDevices_MotorGearSet
#define TerriBullDevices_MotorDevice_break_mode_ENUMTYPE TerriBullDevices_MotorBrakeMode




#define TerriBullDevices_MotorInitializeCallbackData_GEAR_SET_ENUMTYPE TerriBullDevices_MotorGearSet
#define TerriBullDevices_MotorInitializeCallbackData_BREAK_MODE_ENUMTYPE TerriBullDevices_MotorBrakeMode





/* Initializer values for message structs */
#define TerriBullDevices_DeviceHeader_init_default {_TerriBullDevices_DeviceType_MIN, 0}
#define TerriBullDevices_MotorDevice_init_default {false, TerriBullDevices_DeviceHeader_init_default, 0, 0, _TerriBullDevices_MotorGearSet_MIN, _TerriBullDevices_MotorBrakeMode_MIN}
#define TerriBullDevices_IMUAccel_init_default   {0, 0, 0}
#define TerriBullDevices_IMUDevice_init_default  {false, TerriBullDevices_DeviceHeader_init_default, 0, 0, 0, false, TerriBullDevices_IMUAccel_init_default}
#define TerriBullDevices_AnalogDevice_init_default {false, TerriBullDevices_DeviceHeader_init_default, 0}
#define TerriBullDevices_MotorInitializeCallbackData_init_default {0, _TerriBullDevices_MotorGearSet_MIN, _TerriBullDevices_MotorBrakeMode_MIN}
#define TerriBullDevices_MotorSetVelocityCallbackData_init_default {0, 0}
#define TerriBullDevices_DeviceValue_init_default {0, {TerriBullDevices_MotorDevice_init_default}}
#define TerriBullDevices_FunctionCall_init_default {0, {TerriBullDevices_MotorInitializeCallbackData_init_default}}
#define TerriBullDevices_DeviceHeader_init_zero  {_TerriBullDevices_DeviceType_MIN, 0}
#define TerriBullDevices_MotorDevice_init_zero   {false, TerriBullDevices_DeviceHeader_init_zero, 0, 0, _TerriBullDevices_MotorGearSet_MIN, _TerriBullDevices_MotorBrakeMode_MIN}
#define TerriBullDevices_IMUAccel_init_zero      {0, 0, 0}
#define TerriBullDevices_IMUDevice_init_zero     {false, TerriBullDevices_DeviceHeader_init_zero, 0, 0, 0, false, TerriBullDevices_IMUAccel_init_zero}
#define TerriBullDevices_AnalogDevice_init_zero  {false, TerriBullDevices_DeviceHeader_init_zero, 0}
#define TerriBullDevices_MotorInitializeCallbackData_init_zero {0, _TerriBullDevices_MotorGearSet_MIN, _TerriBullDevices_MotorBrakeMode_MIN}
#define TerriBullDevices_MotorSetVelocityCallbackData_init_zero {0, 0}
#define TerriBullDevices_DeviceValue_init_zero   {0, {TerriBullDevices_MotorDevice_init_zero}}
#define TerriBullDevices_FunctionCall_init_zero  {0, {TerriBullDevices_MotorInitializeCallbackData_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define TerriBullDevices_DeviceHeader_pros_device_type_tag 1
#define TerriBullDevices_DeviceHeader_port_tag   2
#define TerriBullDevices_MotorDevice_header_tag  1
#define TerriBullDevices_MotorDevice_velocity_tag 2
#define TerriBullDevices_MotorDevice_current_draw_tag 3
#define TerriBullDevices_MotorDevice_gear_set_tag 4
#define TerriBullDevices_MotorDevice_break_mode_tag 5
#define TerriBullDevices_IMUAccel_ax_tag         1
#define TerriBullDevices_IMUAccel_ay_tag         2
#define TerriBullDevices_IMUAccel_az_tag         3
#define TerriBullDevices_IMUDevice_header_tag    1
#define TerriBullDevices_IMUDevice_roll_tag      2
#define TerriBullDevices_IMUDevice_yaw_tag       3
#define TerriBullDevices_IMUDevice_pitch_tag     4
#define TerriBullDevices_IMUDevice_accel_tag     5
#define TerriBullDevices_AnalogDevice_header_tag 1
#define TerriBullDevices_AnalogDevice_value_tag  2
#define TerriBullDevices_MotorInitializeCallbackData_port_tag 1
#define TerriBullDevices_MotorInitializeCallbackData_GEAR_SET_tag 2
#define TerriBullDevices_MotorInitializeCallbackData_BREAK_MODE_tag 3
#define TerriBullDevices_MotorSetVelocityCallbackData_port_tag 1
#define TerriBullDevices_MotorSetVelocityCallbackData_velocity_tag 2
#define TerriBullDevices_DeviceValue_motorDevice_tag 1
#define TerriBullDevices_DeviceValue_imuDevice_tag 2
#define TerriBullDevices_DeviceValue_analogDevice_tag 3
#define TerriBullDevices_FunctionCall_motorInitializeData_tag 1
#define TerriBullDevices_FunctionCall_motorSetVelocityData_tag 2

/* Struct field encoding specification for nanopb */
#define TerriBullDevices_DeviceHeader_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    pros_device_type,   1) \
X(a, STATIC,   SINGULAR, UINT32,   port,              2)
#define TerriBullDevices_DeviceHeader_CALLBACK NULL
#define TerriBullDevices_DeviceHeader_DEFAULT NULL

#define TerriBullDevices_MotorDevice_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, FLOAT,    velocity,          2) \
X(a, STATIC,   SINGULAR, FLOAT,    current_draw,      3) \
X(a, STATIC,   SINGULAR, UENUM,    gear_set,          4) \
X(a, STATIC,   SINGULAR, UENUM,    break_mode,        5)
#define TerriBullDevices_MotorDevice_CALLBACK NULL
#define TerriBullDevices_MotorDevice_DEFAULT NULL
#define TerriBullDevices_MotorDevice_header_MSGTYPE TerriBullDevices_DeviceHeader

#define TerriBullDevices_IMUAccel_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    ax,                1) \
X(a, STATIC,   SINGULAR, FLOAT,    ay,                2) \
X(a, STATIC,   SINGULAR, FLOAT,    az,                3)
#define TerriBullDevices_IMUAccel_CALLBACK NULL
#define TerriBullDevices_IMUAccel_DEFAULT NULL

#define TerriBullDevices_IMUDevice_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, FLOAT,    roll,              2) \
X(a, STATIC,   SINGULAR, FLOAT,    yaw,               3) \
X(a, STATIC,   SINGULAR, FLOAT,    pitch,             4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  accel,             5)
#define TerriBullDevices_IMUDevice_CALLBACK NULL
#define TerriBullDevices_IMUDevice_DEFAULT NULL
#define TerriBullDevices_IMUDevice_header_MSGTYPE TerriBullDevices_DeviceHeader
#define TerriBullDevices_IMUDevice_accel_MSGTYPE TerriBullDevices_IMUAccel

#define TerriBullDevices_AnalogDevice_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, FLOAT,    value,             2)
#define TerriBullDevices_AnalogDevice_CALLBACK NULL
#define TerriBullDevices_AnalogDevice_DEFAULT NULL
#define TerriBullDevices_AnalogDevice_header_MSGTYPE TerriBullDevices_DeviceHeader

#define TerriBullDevices_MotorInitializeCallbackData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   port,              1) \
X(a, STATIC,   SINGULAR, UENUM,    GEAR_SET,          2) \
X(a, STATIC,   SINGULAR, UENUM,    BREAK_MODE,        3)
#define TerriBullDevices_MotorInitializeCallbackData_CALLBACK NULL
#define TerriBullDevices_MotorInitializeCallbackData_DEFAULT NULL

#define TerriBullDevices_MotorSetVelocityCallbackData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   port,              1) \
X(a, STATIC,   SINGULAR, INT32,    velocity,          2)
#define TerriBullDevices_MotorSetVelocityCallbackData_CALLBACK NULL
#define TerriBullDevices_MotorSetVelocityCallbackData_DEFAULT NULL

#define TerriBullDevices_DeviceValue_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (device,motorDevice,device.motorDevice),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (device,imuDevice,device.imuDevice),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (device,analogDevice,device.analogDevice),   3)
#define TerriBullDevices_DeviceValue_CALLBACK NULL
#define TerriBullDevices_DeviceValue_DEFAULT NULL
#define TerriBullDevices_DeviceValue_device_motorDevice_MSGTYPE TerriBullDevices_MotorDevice
#define TerriBullDevices_DeviceValue_device_imuDevice_MSGTYPE TerriBullDevices_IMUDevice
#define TerriBullDevices_DeviceValue_device_analogDevice_MSGTYPE TerriBullDevices_AnalogDevice

#define TerriBullDevices_FunctionCall_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (callbackData,motorInitializeData,callbackData.motorInitializeData),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (callbackData,motorSetVelocityData,callbackData.motorSetVelocityData),   2)
#define TerriBullDevices_FunctionCall_CALLBACK NULL
#define TerriBullDevices_FunctionCall_DEFAULT NULL
#define TerriBullDevices_FunctionCall_callbackData_motorInitializeData_MSGTYPE TerriBullDevices_MotorInitializeCallbackData
#define TerriBullDevices_FunctionCall_callbackData_motorSetVelocityData_MSGTYPE TerriBullDevices_MotorSetVelocityCallbackData

extern const pb_msgdesc_t TerriBullDevices_DeviceHeader_msg;
extern const pb_msgdesc_t TerriBullDevices_MotorDevice_msg;
extern const pb_msgdesc_t TerriBullDevices_IMUAccel_msg;
extern const pb_msgdesc_t TerriBullDevices_IMUDevice_msg;
extern const pb_msgdesc_t TerriBullDevices_AnalogDevice_msg;
extern const pb_msgdesc_t TerriBullDevices_MotorInitializeCallbackData_msg;
extern const pb_msgdesc_t TerriBullDevices_MotorSetVelocityCallbackData_msg;
extern const pb_msgdesc_t TerriBullDevices_DeviceValue_msg;
extern const pb_msgdesc_t TerriBullDevices_FunctionCall_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define TerriBullDevices_DeviceHeader_fields &TerriBullDevices_DeviceHeader_msg
#define TerriBullDevices_MotorDevice_fields &TerriBullDevices_MotorDevice_msg
#define TerriBullDevices_IMUAccel_fields &TerriBullDevices_IMUAccel_msg
#define TerriBullDevices_IMUDevice_fields &TerriBullDevices_IMUDevice_msg
#define TerriBullDevices_AnalogDevice_fields &TerriBullDevices_AnalogDevice_msg
#define TerriBullDevices_MotorInitializeCallbackData_fields &TerriBullDevices_MotorInitializeCallbackData_msg
#define TerriBullDevices_MotorSetVelocityCallbackData_fields &TerriBullDevices_MotorSetVelocityCallbackData_msg
#define TerriBullDevices_DeviceValue_fields &TerriBullDevices_DeviceValue_msg
#define TerriBullDevices_FunctionCall_fields &TerriBullDevices_FunctionCall_msg

/* Maximum encoded size of messages (where known) */
#define TERRIBULLDEVICES_INCLUDE_PROTOS_VEX_PB_H_MAX_SIZE TerriBullDevices_DeviceValue_size
#define TerriBullDevices_AnalogDevice_size       16
#define TerriBullDevices_DeviceHeader_size       9
#define TerriBullDevices_DeviceValue_size        45
#define TerriBullDevices_FunctionCall_size       19
#define TerriBullDevices_IMUAccel_size           15
#define TerriBullDevices_IMUDevice_size          43
#define TerriBullDevices_MotorDevice_size        29
#define TerriBullDevices_MotorInitializeCallbackData_size 14
#define TerriBullDevices_MotorSetVelocityCallbackData_size 17

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
