/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "include/protos/vex.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(TerriBullDevices_DeviceHeader, TerriBullDevices_DeviceHeader, AUTO)


PB_BIND(TerriBullDevices_MotorDevice, TerriBullDevices_MotorDevice, AUTO)


PB_BIND(TerriBullDevices_IMUAccel, TerriBullDevices_IMUAccel, AUTO)


PB_BIND(TerriBullDevices_IMUDevice, TerriBullDevices_IMUDevice, AUTO)


PB_BIND(TerriBullDevices_AnalogDevice, TerriBullDevices_AnalogDevice, AUTO)


PB_BIND(TerriBullDevices_MotorInitializeCallbackData, TerriBullDevices_MotorInitializeCallbackData, AUTO)


PB_BIND(TerriBullDevices_MotorSetVelocityCallbackData, TerriBullDevices_MotorSetVelocityCallbackData, AUTO)


PB_BIND(TerriBullDevices_DeviceValue, TerriBullDevices_DeviceValue, AUTO)


PB_BIND(TerriBullDevices_FunctionCall, TerriBullDevices_FunctionCall, AUTO)


PB_BIND(TerriBullDevices_ReturnData, TerriBullDevices_ReturnData, AUTO)







